
language: python
python:
  - "2.7"
matrix:
  include:
    - os: linux
      dist: trusty

# command to install dependencies
install: 
  - pip install scipy
  - pip install -r requirements.txt
# command to run tests
script: . travis.sh
branches:
  only:
    - master
    - v1-dev
    - v1-dev-aaron
