
language: python

dist: trusty

python:
  - "2.7"
os: 
  - linux
virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: . travis.sh
branches:
  only:
    - master
    - v1-dev
    - v1-dev-aaron
