language: python

python:
  - "2.7"
os: 
  - linux

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get build-dep python-scipy
 - sudo pip install scipy
 # - sudo apt-get install -qq python-numpy python-scipy

# command to install dependencies
install:
  - sudo python setup.py install
  # make sure that scipy is OK before anything else
  - python -c "import scipy"

# command to run tests
script: . run_test.sh
branches:
  only:
    - master
    - v1-dev